### ISSUE TITLE
Notification of successful transactions

### ISSUE THREAD

**Issue by komlosboldizsar** [thatsbenedek/becskassza#1]
Dear Valued Developer,

I use your simple application a lot and find it very useful, but I'm missing an important feature. There is no feedback if a transaction (e.g. buying a beer) happened and was successful. I'd need a notification, or maybe a history with the last X (5?) events (event type, product name, amount) would be much better, I think.

Could you please add this feature or something similar to the application?

I'm very thankful for your work and help.
Have a nice day and kind regards,
gróf id. Boldizsár de la Budavári Schönherz Stúdió 'n' Lapszabászat 'n' Romkocsma

**Comment by thatsbenedek** [comment]
Dear Valued User,

Check out release v1.0.1, in which I improved the feedback of successful transactions.
To update your app, open it from the home screen, and swipe down from the top.

Thank you for using the app, and taking time submit this issue.

Kind regards,
Benedek Kozma
